// eslint-disable-next-line import/prefer-default-export
export const paymentSystems = {
  2: 'mir',
  30: 'diners-club',
  31: 'jcb',
  35: 'jcb',
  34: 'american-express',
  36: 'diners-club',
  37: 'american-express',
  38: 'diners-club',
  4: 'visa',
  50: 'maestro',
  51: 'mastercard',
  52: 'mastercard',
  53: 'mastercard',
  54: 'mastercard',
  55: 'mastercard',
  56: 'maestro',
  57: 'maestro',
  58: 'maestro',
  60: 'discover',
  62: 'union-pay',
  63: 'maestro',
  67: 'maestro',
};
